### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SeanPedersen** [gwax/pylint-sqlalchemy#1]
This package did not do the advertised job of making pylint work with sqlalchemy for following code example: https://pythonhosted.org/Flask-Security/quickstart.html#id4
In particular for following method call:
`db_session.commit()`
PyLint would still report: Instance of 'scoped_session' has no 'commit' member

But this one (same name) did do the job: https://github.com/lagelalegal/pylint-sqlalchemy
Installed via: `$ pip install -e git+https://github.com/lagelalegal/pylint-sqlalchemy.git#egg=pylint_sqlalchemy`

and used as: `$ pylint -E --load-plugins pylint_sqlalchemy *.py`

I suggest to merge best functionalities of both.

**Comment by lagelalegal** [comment]
@gwax Hello man, your 'Pylint-sqlalchemy' bag is not working. But pylint-sqlalchemy' 's name is yours. Now, I want to merge my project with you. What do you think?

**Comment by SeanPedersen** [comment]
Good effort guys, appreciate it!

**Comment by gwax** [comment]
I am going to reopen the issue and keep it open until the resolving PR is merged.

**Comment by gwax** [comment]
#2 has been merged and this issue _should_ be resolved. Please pip install the latest version and reopen if it does not work.
